# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: false
r:
  - oldrel

after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - Rscript -e 'install.packages(c("roxygen2", "devtools", "Rcpp"))'
