d = 2
m = d*200
train <- matrix(runif(m*40, -1000, 1000), m, 40)
test <- matrix(runif(m/10*40, -1000, 1000), m/10, 40)
cl <- factor(c(rep(1,m/d), rep(2,m/d)))

train1 = rbind(iris3[1:25,,1], iris3[1:25,,2], iris3[1:25,,3])
test1 = rbind(iris3[26:50,,1], iris3[26:50,,2], iris3[26:50,,3])
cl1 = factor(c(rep("s",25), rep("c",25), rep("v",25)))
test_that("kNN works", {
  expect_equal(as.character(kNN(train1, test1, cl1, k = 5, prob=TRUE, use.all = T)), c("s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "c", "c", "v", "c", "c", "c", "c", "c", "v", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "v", "c", "c", "v", "v", "v", "v", "v", "c", "v", "v", "v", "v", "c", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v" ))
  expect_equal(as.character(kNN_R(train1, test1, cl1, k = 5, prob=TRUE, use.all = T)), c("s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "c", "c", "v", "c", "c", "c", "c", "c", "v", "v", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "v", "c", "v", "v", "v", "v", "v", "v", "c", "c", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v" ))
  expect_equal(as.character(kNN(train1, test1, cl1, k = 9, prob=TRUE, use.all = F)), c("s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "c", "c", "c", "c", "c", "c", "c", "c", "v", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "v", "c", "v", "v", "v", "v", "v", "v", "c", "v", "v", "v", "v", "c", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v"))
  expect_equal(as.character(kNN_R(train1, test1, cl1, k = 9, prob=TRUE, use.all = F)), c("s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "c", "c", "c", "c", "c", "c", "c", "c", "v", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "v", "c", "v", "v", "v", "v", "v", "v", "c", "v", "v", "v", "v", "c", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v" ))
  expect_equal(kNN(train, test, cl, k = 9, prob=TRUE, use.all = F), kNN_R(train, test, cl, k = 9, prob=TRUE, use.all = F))
  expect_equal(as.character(kNN(train1, test1[1,], cl1, k = 9, prob=TRUE, use.all = F)), "s")
  expect_equal(as.character(kNN_R(train1, test1[1,], cl1, k = 9, prob=TRUE, use.all = F)), "s")
  expect_error(kNN(cl, test, cl, k = 9, prob=TRUE, use.all = F), "'train' is not a matrix!")
  expect_error(kNN_R(cl, test, cl, k = 9, prob=TRUE, use.all = F), "'train' is not a matrix!")
  expect_error(kNN(train, c(NA,NA), cl, k = 9, prob=TRUE, use.all = F), "There is missing value which is not allowed!")
  expect_error(kNN_R(train, c(NA,NA), cl, k = 9, prob=TRUE, use.all = F), "There is missing value which is not allowed!")
  expect_error(kNN(train, test, cl[1], k = 9, prob=TRUE, use.all = F), "The number of 'train' samples and the number of 'class' should match!")
  expect_error(kNN_R(train, test, cl[1], k = 9, prob=TRUE, use.all = F), "The number of 'train' samples and the number of 'class' should match!")
  expect_warning(kNN(train, test, cl, k = 9000, prob=TRUE, use.all = F), "k exceeds number of 'train' samples!")
  expect_warning(kNN_R(train, test, cl, k = 9000, prob=TRUE, use.all = F), "k exceeds number of 'train' samples!")
  expect_error(kNN(train, test, cl, k = 0, prob=TRUE, use.all = F), "k cannot be less than 1!")
  expect_error(kNN_R(train, test, cl, k = 0, prob=TRUE, use.all = F), "k cannot be less than 1!")
  expect_error(kNN(train, test[1,1:2], cl, k = 2, prob=TRUE, use.all = F), "The dimensions of 'test' and 'train' do not match!")
  expect_error(kNN_R(train, test[1,1:2], cl, k = 2, prob=TRUE, use.all = F), "The dimensions of 'test' and 'train' do not match!")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, prob=TRUE, use.all = F)), "s")
  expect_equal(as.character(kNN_R(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, prob=TRUE, use.all = F)), "s")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, l = 3, prob=TRUE, use.all = F)), "s")
  expect_equal(as.character(kNN_R(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, l = 3, prob=TRUE, use.all = F)), "c")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, prob=TRUE, use.all = T)), "s")
  expect_equal(as.character(kNN_R(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, prob=TRUE, use.all = T)), "s")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 1, prob=TRUE, use.all = T)), "s")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 2, prob=TRUE, use.all = T)), "s")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 3, prob=TRUE, use.all = T)), "s")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 4, prob=TRUE, use.all = T)), "s")
  expect_equal(as.character(kNN(rbind(train1, train1, train1, train1), test1[1,], rep(cl1, 4), k = 5, prob=TRUE, use.all = T)), "s")

})
