# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_knn_search <- function(k_in, l_in, ntrain, dim, train, cls, test, res, pr, ncls, use_all, begin, end) {
    invisible(.Call(`_kNN_C_knn_search`, k_in, l_in, ntrain, dim, train, cls, test, res, pr, ncls, use_all, begin, end))
}

C_kNN_multi_thread <- function(k_in, l_in, ntrain, dim, train, cls, test, ncls, use_all) {
    .Call(`_kNN_C_kNN_multi_thread`, k_in, l_in, ntrain, dim, train, cls, test, ncls, use_all)
}

